#!/usr/bin/env bash
#
# build-stress-fixtures.sh — build XFS filesystems whose contents were
# decided by a stress generator rather than by hand.
#
# scripts/vm-build-data-fixtures.sh writes a tree somebody sat down and
# thought of: a small file, a big file, a sparse file, 400 directory
# entries. That is a good tree, and it is also a tree shaped by the same
# assumptions the driver was written under. It will never contain the
# case nobody thought of.
#
# These two fixtures are shaped by `fsstress` and `fsx`, the two stress
# generators from the filesystem test suite (fstests). `fsstress` runs a
# long randomised sequence of filesystem operations — create, link,
# rename, truncate, punch, collapse, insert, mknod, setxattr — against a
# mounted filesystem. `fsx` hammers a single file with randomised reads,
# writes, truncates, hole punches, range clones and mmap operations. The
# on-disk states that come out are far more awkward than anything worth
# writing by hand, and they are produced without reference to what this
# driver happens to find easy.
#
# The suite is NOT run against this driver, and cannot be: it exercises a
# mounted filesystem through the kernel's VFS, and this driver is a
# userspace library. The relationship is the other way round — the
# generator decides what goes on the disk, and the kernel and
# `xfs_repair` remain the only judges of what is on it. That is the same
# arrangement every other fixture here uses; this only widens the input.
#
# LICENSING. fstests is GPL-2.0. Its binaries are executed; nothing from
# it is copied, quoted or adapted into this repository, and its source
# and build tree live only in the guest. Running a program does not make
# the caller a derivative work of it. See
# tests/vagrant/debian/provision-stress-tools.sh, which builds it — the
# same script a CI runner uses, since it is plain apt and make.
#
# REPRODUCIBILITY. Both generators take a seed and an operation count,
# and both are given fixed ones below with a single worker process. A
# fixture nobody can rebuild is an anecdote, not a test — and a failure
# found against one is not something anyone can bisect. Change the seed
# only deliberately, and expect every manifest to change with it.
set -euo pipefail

# WHERE THIS RUNS. Anywhere with xfsprogs, fsstress, fsx, filefrag and
# the privilege to loop-mount: a CI runner, a container, or the oracle
# VM. `vm-build-stress-fixtures.sh` ships this same file into the VM, so
# the two cannot drift.
#
# The generators are built by tests/vagrant/debian/provision-stress-tools.sh,
# which is apt and make and runs on a runner unchanged.

OUT="${XFS_FIXTURE_DIR:-$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)/.vm-share}"

# The fixed inputs. Stated here, recorded in each fixture's .provenance,
# and asserted by tests/stress_oracle.rs.
SEED=20260826
FSSTRESS_OPS=5000
FSX_OPS=20000
FSX_MAXLEN=4194304   # 4 MiB upper bound on the hammered file's length
IMAGE_SIZE=500M      # mkfs.xfs refuses anything under ~300 MB

# Built on local storage rather than in the output directory. The
# generators issue tens of thousands of small writes with fsyncs between
# them, and driving that through the VM's host share turns a one-minute
# build into a much longer one; xfs_repair cannot open a file there at
# all. The finished image is copied across at the end.
WORK="${XFS_STRESS_WORK:-/var/tmp/xfs-stress}"

SUDO=""
[ "$(id -u)" -eq 0 ] || SUDO="sudo"

for tool in mkfs.xfs xfs_repair fsstress fsx filefrag; do
    command -v "$tool" >/dev/null || {
        echo "$tool not found. xfsprogs and e2fsprogs from the distribution;" >&2
        echo "fsstress and fsx from tests/vagrant/debian/provision-stress-tools.sh" >&2
        exit 1
    }
done

mkdir -p "$OUT" "$WORK"

# record_fixture <case-name> <image> <generator-line>
#
# The manifest is generated by the kernel's own XFS driver, on a
# read-only mount so the image stays byte-identical to what the
# generator left behind: one line per path, tab separated, as
#
#     <path>\t<type>\t<size>\t<detail>
#
# with dir, link (detail is the target) and file (detail is the
# SHA-256), plus the four a hand-written tree never produces and
# fsstress's `mknod` does: chr, blk, fifo and sock. Nothing in this
# repository decides what the right answer is.
record_fixture() {
    local name="$1" img="$2" generator="$3"
    local base="$WORK/$name"

    # Read-only, and norecovery: the log was left clean by the unmount
    # above, and this must not be the thing that changes the image.
    local mnt; mnt=$(mktemp -d)
    $SUDO mount -o ro,norecovery,loop "$img" "$mnt"
    (
        cd "$mnt"
        $SUDO find . -mindepth 1 | sort | while read -r p; do
            rel="${p#.}"
            if   [ -L "$p" ]; then printf '%s\tlink\t0\t%s\n' "$rel" "$(readlink "$p")"
            elif [ -d "$p" ]; then printf '%s\tdir\t0\t-\n'   "$rel"
            elif [ -f "$p" ]; then
                printf '%s\tfile\t%s\t%s\n' "$rel" \
                       "$(stat -c%s "$p")" "$(sha256sum "$p" | cut -d' ' -f1)"
            elif [ -c "$p" ]; then printf '%s\tchr\t0\t-\n'  "$rel"
            elif [ -b "$p" ]; then printf '%s\tblk\t0\t-\n'  "$rel"
            elif [ -p "$p" ]; then printf '%s\tfifo\t0\t-\n' "$rel"
            elif [ -S "$p" ]; then printf '%s\tsock\t0\t-\n' "$rel"
            else                   printf '%s\tunknown\t0\t-\n' "$rel"
            fi
        done
    ) | $SUDO tee "$base.manifest" > /dev/null

    # What shape the fixture actually came out. A stress run is random: a
    # seed that happened to produce a flat tree of ten empty files would
    # leave the oracle test green while testing nothing, so the counts
    # are recorded and tests/stress_oracle.rs insists on them.
    #
    # Extent counts come from FIEMAP via the reference tool rather than
    # from this driver, for the same reason as everything else here.
    local extents_max=0 extents_file="-" sparse=0
    while read -r f; do
        local n sz blk
        n=$($SUDO filefrag "$mnt$f" 2>/dev/null | sed -n 's/.*: \([0-9]*\) extents\? found.*/\1/p' | head -1)
        [ -n "$n" ] || continue
        if [ "$n" -gt "$extents_max" ]; then extents_max=$n; extents_file=$f; fi
        sz=$($SUDO stat -c%s "$mnt$f"); blk=$($SUDO stat -c%b "$mnt$f")
        # 512-byte blocks. Fewer allocated than the length implies holes.
        if [ "$sz" -gt $(( blk * 512 )) ]; then sparse=$(( sparse + 1 )); fi
    done < <(awk -F'\t' '$2 == "file" { print $1 }' "$base.manifest")
    $SUDO umount "$mnt"; rmdir "$mnt"

    {
        printf 'case=%s\n' "$name"
        printf 'generator=%s\n' "$generator"
        printf 'seed=%s\n' "$SEED"
        printf 'fstests=%s\n' "$(cat /usr/local/share/fstests-generators.version 2>/dev/null || echo unknown)"
        printf 'mkfs=%s\n' "$(mkfs.xfs -V 2>&1 | head -1)"
        printf 'kernel=%s\n' "$(uname -r)"
        printf 'entries=%s\n'    "$(wc -l < "$base.manifest")"
        printf 'dirs=%s\n'       "$(awk -F'\t' '$2=="dir"  {n++} END {print n+0}' "$base.manifest")"
        printf 'files=%s\n'      "$(awk -F'\t' '$2=="file" {n++} END {print n+0}' "$base.manifest")"
        printf 'symlinks=%s\n'   "$(awk -F'\t' '$2=="link" {n++} END {print n+0}' "$base.manifest")"
        printf 'chardevs=%s\n'   "$(awk -F'\t' '$2=="chr"  {n++} END {print n+0}' "$base.manifest")"
        printf 'blockdevs=%s\n'  "$(awk -F'\t' '$2=="blk"  {n++} END {print n+0}' "$base.manifest")"
        printf 'fifos=%s\n'      "$(awk -F'\t' '$2=="fifo" {n++} END {print n+0}' "$base.manifest")"
        printf 'sockets=%s\n'    "$(awk -F'\t' '$2=="sock" {n++} END {print n+0}' "$base.manifest")"
        printf 'filebytes=%s\n'  "$(awk -F'\t' '$2=="file" {s+=$3} END {print s+0}' "$base.manifest")"
        printf 'sparsefiles=%s\n' "$sparse"
        printf 'maxextents=%s\n' "$extents_max"
        printf 'maxextentsfile=%s\n' "$extents_file"
    } > "$base.provenance"

    # The reference checker's verdict on the fixture itself. A generator
    # is perfectly capable of tripping over a kernel bug and leaving a
    # genuinely broken filesystem behind; if that ever happens the
    # fixture must be rejected here rather than blamed on the driver.
    local rc
    xfs_repair -n "$img" > "$base.repair" 2>&1 && rc=0 || rc=$?
    if [ "$rc" -eq 0 ] && ! grep -qiE 'corrupt|bad magic|would (fix|correct|rebuild|reset)' "$base.repair"; then
        echo SOUND > "$base.verdict"
    else
        echo BROKEN > "$base.verdict"
    fi
}

# ---------------------------------------------------------------------
# Case `ops`: a whole tree built by fsstress.
#
# The default operation mix is used unchanged. It is tempting to switch
# off the operations this driver finds least interesting -- `mknod` alone
# accounts for a third of the entries -- but a mix chosen by whoever is
# writing the fixture is exactly the hand-shaped input this is meant to
# get away from. One worker process, so the order of operations is
# decided by the seed and nothing else.
#
# Built twice, at two block sizes. That is not thoroughness for its own
# sake: a symlink target longer than one block's worth is stored across
# several, and reassembling those is a distinct code path with its own
# way of going wrong. At 4 KiB, fsstress's longest target still fits one
# block and that path never runs. At 1 KiB it takes three.
# ---------------------------------------------------------------------
for variant in "ops:" "ops1k:-b size=1024"; do
    case_name="${variant%%:*}"
    mkfs_args="${variant#*:}"

    img="$WORK/$case_name.img"
    rm -f "$WORK/$case_name".*
    truncate -s "$IMAGE_SIZE" "$img"
    # shellcheck disable=SC2086
    mkfs.xfs -f -q $mkfs_args "$img" >/dev/null 2>&1

    mnt=$(mktemp -d)
    $SUDO mount -o loop "$img" "$mnt"
    $SUDO mkdir -p "$mnt/stress"
    # fsstress exits non-zero on an operation the filesystem declined,
    # which is ordinary -- the point is the state it leaves behind.
    $SUDO fsstress -d "$mnt/stress" -n "$FSSTRESS_OPS" -p 1 -s "$SEED" \
        > "$WORK/$case_name.fsstress.log" 2>&1 || true
    sync
    $SUDO umount "$mnt"; rmdir "$mnt"

    record_fixture "$case_name" "$img" "fsstress -n $FSSTRESS_OPS -p 1 -s $SEED $mkfs_args"

    cp --sparse=always "$img" "$OUT/xfsstress-$case_name.img"
    for ext in manifest provenance repair verdict; do
        cp "$WORK/$case_name.$ext" "$OUT/xfsstress-$case_name.$ext"
    done
    echo "BUILT xfsstress-$case_name ($(wc -l < "$WORK/$case_name.manifest") entries, xfs_repair says $(cat "$WORK/$case_name.verdict"))"
done

# ---------------------------------------------------------------------
# Case `fsx`: one file, hammered.
#
# fsx keeps its own model of what the file should contain and verifies
# after every operation, so a run that completes is a file the kernel
# agrees with byte for byte. What it leaves behind is a small file with
# an absurd extent layout -- interleaved written ranges, punched holes,
# collapsed and inserted ranges, and tails left by truncation -- which is
# precisely the shape a hand-written fixture never reaches.
# ---------------------------------------------------------------------
mkdir -p "$WORK/fsxlogs"
img="$WORK/fsx.img"
rm -f "$WORK/fsx.img" "$WORK/fsx.manifest" "$WORK/fsx.provenance" \
      "$WORK/fsx.repair" "$WORK/fsx.verdict"
truncate -s "$IMAGE_SIZE" "$img"
mkfs.xfs -f -q "$img" >/dev/null 2>&1

mnt=$(mktemp -d)
$SUDO mount -o loop "$img" "$mnt"
$SUDO mkdir -p "$mnt/fsx"
# Its own logs must not become part of the fixture, so they are kept off
# the filesystem under test.
if $SUDO fsx -N "$FSX_OPS" -S "$SEED" -l "$FSX_MAXLEN" -P "$WORK/fsxlogs" -q \
       "$mnt/fsx/hammered.bin" > "$WORK/fsx.fsx.log" 2>&1; then
    :
else
    # fsx failing means fsx and the kernel disagree about the file it
    # just wrote. That is not this driver's problem and the fixture must
    # not be built from it.
    echo 'fsx and the kernel disagreed; refusing to build a fixture from it:'
    tail -20 "$WORK/fsx.fsx.log"
    $SUDO umount "$mnt"; rmdir "$mnt"
    exit 1
fi
sync
$SUDO umount "$mnt"; rmdir "$mnt"

record_fixture fsx "$img" "fsx -N $FSX_OPS -S $SEED -l $FSX_MAXLEN"

cp --sparse=always "$img" "$OUT/xfsstress-fsx.img"
for ext in manifest provenance repair verdict; do
    cp "$WORK/fsx.$ext" "$OUT/xfsstress-fsx.$ext"
done
echo "BUILT xfsstress-fsx ($(sed -n 's/^maxextents=//p' "$WORK/fsx.provenance") extents, xfs_repair says $(cat "$WORK/fsx.verdict"))"

echo
echo "Stress fixtures in $OUT:"
ls -1 "$OUT"/xfsstress-*.img 2>/dev/null || echo "  (none)"
