#!/usr/bin/env bash
#
# build-data-fixtures.sh — build POPULATED XFS filesystems together
# with a manifest of their contents generated by the Linux kernel
# itself.
#
# scripts/vm-build-fixtures.sh produces freshly-made filesystems, which
# have an empty short-form root directory and no file data at all. Those
# validate the superblock and AG headers and nothing else.
#
# These fixtures are mounted and written to, so they exercise the parts
# of the driver a user actually depends on: extent lists, multi-block
# files, sparse files, symlinks in both storage forms, and directories
# large enough to leave short form behind.
#
# The manifest beside each image is produced INSIDE Linux by the
# kernel's own XFS driver -- path, type, size and SHA-256 per entry.
# Nothing in this repository decides what the right answer is, which is
# the entire point: tests/endtoend_oracle.rs requires this driver to
# reproduce it byte for byte.
set -euo pipefail

# WHERE THIS RUNS. Anywhere with xfsprogs, attr, python3 and the
# privilege to loop-mount: a CI runner, a container, or the oracle VM.
# `vm-build-data-fixtures.sh` ships this same file into the VM, so the
# two cannot drift.

OUT="${XFS_FIXTURE_DIR:-$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)/.vm-share}"

SUDO=""
[ "$(id -u)" -eq 0 ] || SUDO="sudo"

for tool in mkfs.xfs xfs_db xfs_io python3; do
    command -v "$tool" >/dev/null || { echo "$tool not found (xfsprogs, python3)" >&2; exit 1; }
done

mkdir -p "$OUT"
cd "$OUT"

# "<name>:<mkfs.xfs args>"
#
# rmapbt=0 throughout: write_oracle mounts these read-write, and this
# driver refuses a reverse-mapping filesystem because it does not
# maintain the tree. Modern mkfs.xfs turns it on by default.
GEOMETRIES=(
    "default:-m rmapbt=0"
    "1k:-b size=1024 -m rmapbt=0"
    "ftype:-m crc=1,rmapbt=0"
)

for geom in "${GEOMETRIES[@]}"; do
    name="${geom%%:*}"
    args="${geom#*:}"
    img="xfsdata-$name.img"

    rm -f "$img" "xfsdata-$name.manifest"
    truncate -s 500M "$img"
    # shellcheck disable=SC2086
    if ! mkfs.xfs $args -f -q "$img" >/dev/null 2>&1; then
        rm -f "$img"
        echo "SKIP  $name (mkfs.xfs rejected this geometry)"
        continue
    fi

    mnt=$(mktemp -d)
    $SUDO mount -o loop "$img" "$mnt"

    # A spread chosen to move the parts of the driver that a single
    # small file would leave untouched.
    echo 'hello world' | $SUDO tee "$mnt/small.txt" > /dev/null
    $SUDO dd if=/dev/urandom of="$mnt/medium.bin" bs=4096 count=64 status=none
    $SUDO dd if=/dev/urandom of="$mnt/large.bin" bs=1M count=8 status=none
    $SUDO truncate -s 10M "$mnt/sparse.bin"
    $SUDO ln -s small.txt "$mnt/link-short"
    $SUDO ln -s "$(python3 -c 'print("d/"*80+"deep")')" "$mnt/link-long"
    $SUDO mkdir -p "$mnt/sub/nested"
    echo nested | $SUDO tee "$mnt/sub/nested/file.txt" > /dev/null
    # 400 entries pushes this directory out of short form.
    $SUDO mkdir "$mnt/manyfiles"
    for i in $(seq 1 400); do echo "$i" | $SUDO tee "$mnt/manyfiles/entry-$i.txt" > /dev/null; done
    # A file with more extents than fit in the inode, which is what
    # pushes its data fork from an inline list into a B+tree. Each block
    # is written with a hole in front of it so the extents cannot be
    # merged back into a shorter list.
    for i in $(seq 0 199); do
        $SUDO dd if=/dev/urandom of="$mnt/fragmented.bin" bs=4096 count=1 \
            seek=$((i * 2)) conv=notrunc status=none
    done
    $SUDO setfattr -n user.testattr -v testvalue "$mnt/small.txt" 2>/dev/null || true
    sync
    $SUDO umount "$mnt"; rmdir "$mnt"

    # Manifest, generated by the kernel driver on a read-only mount so
    # the image stays byte-identical to what was just written.
    mnt=$(mktemp -d)
    $SUDO mount -o ro,norecovery,loop "$img" "$mnt"
    ( cd "$mnt"
      $SUDO find . -mindepth 1 | sort | while read -r p; do
        rel="${p#.}"
        if [ -L "$p" ]; then
          printf '%s\tlink\t0\t%s\n' "$rel" "$(readlink "$p")"
        elif [ -d "$p" ]; then
          printf '%s\tdir\t0\t-\n' "$rel"
        else
          printf '%s\tfile\t%s\t%s\n' "$rel" "$(stat -c%s "$p")" "$(sha256sum "$p" | cut -d' ' -f1)"
        fi
      done
    ) > "xfsdata-$name.manifest"
    $SUDO umount "$mnt"; rmdir "$mnt"

    # The root directory dump that tests/dir_oracle.rs compares against,
    # regenerated here so it can never describe an older image than the
    # one beside it. A stale dump is worse than a missing one: it fails
    # on a change that was intended, and passes on one that was not.
    rootino=$(xfs_db -r -c 'sb 0' -c 'print rootino' "$img" 2>/dev/null | \
              sed -n 's/^rootino = //p')
    {
        echo "ROOTINO $rootino"
        xfs_db -r -c "inode $rootino" -c print "$img" 2>/dev/null
    } > "xfsdata-$name.rootdump"

    # Record which inodes ended up in B+tree format, straight from the
    # reference debugger. tests/endtoend_oracle.rs requires this list to
    # be non-empty: if a future mkfs or kernel keeps fragmented.bin as an
    # inline extent list, the fixture has stopped exercising the bmbt
    # walker and must say so rather than passing quietly.
    : > "xfsdata-$name.bmbt"
    for f in fragmented.bin large.bin medium.bin; do
        fmt=$(xfs_db -r -c "path /$f" -c "print core.format" "$img" 2>/dev/null | \
               sed -n 's/^core.format = //p')
        [ -n "$fmt" ] || continue
        printf '%s\t%s\n' "/$f" "$fmt" >> "xfsdata-$name.bmbt"
    done

    echo "BUILT $name ($(wc -l < "xfsdata-$name.manifest") entries, forks: $(tr '\n' ' ' < "xfsdata-$name.bmbt"))"
done

# ---------------------------------------------------------------------
# A filesystem whose log was never replayed.
#
# Everything above is unmounted cleanly, so it can only ever check that a
# clean log is recognised as clean -- which a check that always said
# "clean" would also pass. This one is shut down mid-flight with
# `xfs_io -c shutdown`, the supported way to simulate a crash, so its log
# still holds work the filesystem itself has not seen.
#
# The verdict comes from xfs_repair, not from us: it is the tool that
# decides whether a log needs replaying, and tests/log_oracle.rs requires
# this driver to agree with it.
# ---------------------------------------------------------------------
# Two files: one is mounted and crashed, the other is the snapshot taken
# of it mid-flight and kept as the fixture. Keeping them separate avoids
# replacing a file a loop device still holds open, which leaves
# xfs_repair unable to open it at all.
work=xfsdirty-work.img
img=xfsdirty.img
rm -f "$work" "$img" xfsdirty.verdict xfsdirty.repair
truncate -s 300M "$work"
mkfs.xfs -f -q -m rmapbt=0 "$work" >/dev/null 2>&1
mnt=$(mktemp -d)
$SUDO mount -o loop "$work" "$mnt"

# Work that leaves no unlinked inode behind, which is precisely the case
# the old unlinked-list check could not see: renames, attribute changes
# and fresh allocations, all still owned by the log.
$SUDO mkdir -p "$mnt/d"
for i in $(seq 1 200); do echo "$i" | $SUDO tee "$mnt/d/f-$i" > /dev/null; done
for i in $(seq 1 200); do $SUDO mv "$mnt/d/f-$i" "$mnt/d/renamed-$i"; done
$SUDO chmod 0600 "$mnt/d/renamed-1"

# Force a shutdown so nothing further reaches the disk, then take the
# image while it is STILL MOUNTED. Unmounting first writes the unmount
# record and leaves a clean log however the filesystem was shut down --
# which is what the first attempt at this fixture did, and why it has to
# be a snapshot rather than a copy afterwards.
$SUDO xfs_io -x -c 'shutdown -f' "$mnt" || true
$SUDO cp --sparse=always "$work" "$img"
$SUDO umount -l "$mnt" 2>/dev/null || $SUDO umount "$mnt" 2>/dev/null || true
rmdir "$mnt" 2>/dev/null || true
rm -f "$work"

# What the reference tool says about this log. Its whole output is kept:
# a verdict of CLEAN means the fixture is not testing what it claims, and
# the reason needs to be readable.
#
# xfs_repair runs on a copy on local storage: inside the VM it cannot
# work on a file in the shared folder, where it wants the host
# filesystem's geometry and gets ENOTDIR from 9p.
check=$(mktemp -u /tmp/repair-check-XXXXXX.img)
cp "$img" "$check"
xfs_repair -n "$check" > xfsdirty.repair 2>&1 || true
rm -f "$check"
if grep -qi 'valuable metadata changes in a log\|needs to be replayed\|log which needs' xfsdirty.repair; then
    echo DIRTY > xfsdirty.verdict
else
    echo CLEAN > xfsdirty.verdict
fi
echo "BUILT xfsdirty (xfs_repair says $(cat xfsdirty.verdict))"

echo
echo "Data fixtures in $OUT:"
ls -1 "$OUT"/xfsdata-*.img "$OUT"/xfsdirty.img 2>/dev/null | sed 's|.*/|  |'
