#!/usr/bin/env bash
#
# test-targets.sh unit|images|oracle|kernel — print the `cargo test`
# target arguments for one tier of the suite.
#
#   unit    the library, the binaries, and every tests/*.rs that reaches
#           neither a fixture nor the guest: no tool, no kernel, no VM
#   images  the tests that read a fixture but need no guest — everything
#           a host without KVM (GitHub's arm64 runners) can still run
#   stress  the tests that read the fsstress/fsx corpus, which is the one
#           fixture set `chore fixtures` does not build by default
#   oracle  every tests/*.rs that runs an xfsprogs tool (in the guest)
#   kernel  every tests/*.rs that asks the real kernel to mount, replay
#           or write (in the guest)
#   all     every suite `chore test` runs: the four tiers together, which
#           is every tests/*.rs EXCEPT the stress corpus
#
# DERIVED FROM THE TESTS THEMSELVES, not from a list someone has to keep.
# The old arrangement was that list: ci.yml named thirty-two suites in a
# `for suite in ...` loop, and tests/every_fixture_suite_is_run_gated.rs
# existed to notice when a new suite was left out of it. A suite is now
# in a tier because of what it calls, so it cannot be left out.
#
# A test names a fixture through `common::share()` or by a `.vm-share`
# path, reaches a tool only through `common::oracle` / `parent_oracle` /
# `assert_xfs_repair_clean`, and the kernel only through
# `common::kernel_run` / `guest_script` — the helpers that fail, never
# skip, when the guest or the tool is missing. tests/test_contract.rs
# fails the suite if a test reaches either any other way, so the
# classification cannot drift.
#
# A file that does both is a KERNEL test: the tiers are disjoint so that
# `chore test:oracle` and `chore test:kernel` together run each file
# once.
#
# COMMENTS ARE STRIPPED BEFORE ANY MATCH, and string literals before a
# CALL match. That is not tidiness. Two suites here are ABOUT these
# patterns rather than users of them — tests/test_contract.rs, which
# refuses every other way of reaching a tool, and
# tests/every_fixture_suite_is_run_gated.rs, which checks this very
# classification — and both name `kernel_run(` in prose and in string
# constants. Matching those put the second in the `kernel` tier, where it
# would have waited for a VM it never speaks to.
#
# A fixture path is the other way round: `.vm-share/xfs-default.img` is a
# string literal and always will be, so that pattern is matched with the
# literals intact. Over-classifying there is the safe direction — a suite
# lands in a tier that has fixtures rather than in the one CI runs with
# none.
set -euo pipefail

REPO="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd -P)"
# A FIXTURE is reached through common::fixture / fixtures_matching, or
# named by a path. The CALLS are what matters and the path is the older
# spelling, kept because a suite may still build its own name: a local
# `fn share()`, or a literal `.vm-share/xfs-default.img`. Matched with
# comments stripped and string literals intact, because a fixture name
# IS a string literal.
#
# BOTH SPELLINGS, and that is not belt and braces. When the skips were
# removed, three suites stopped naming `.vm-share` at all — the lookup
# they had written by hand became one call to the shared helper — and
# with only the path spelling here they dropped silently into the UNIT
# tier, which CI runs on a runner with no fixtures at all.
FIXTURE='fixture\(|fixtures_matching\(|\.vm-share|share\(\)'
# A TOOL or THE KERNEL is reached by a CALL, so those are matched with
# the literals emptied as well. `"kernel_run("` inside a constant is a
# suite talking about the classifier, not one using it.
TOOL='oracle\(|parent_oracle\(|assert_xfs_repair_clean\('
KERNEL='kernel_run\(|guest_script\('
# THE STRESS CORPUS IS ITS OWN TIER, because it is the one set `chore
# fixtures` does not build: three 500 MB filesystems generated by
# fsstress and fsx, on top of an fstests build, which is tens of minutes
# for a result that is identical every run unless the seed or the tooling
# moves. `.github/workflows/stress.yml` builds it weekly and on demand
# and runs this tier against it.
#
# NAMED, NOT DERIVED, and this is the one place in this file that is.
# The rule everywhere else is "a suite is in a tier because of what it
# calls", and it works because reaching a fixture, a tool or the kernel
# is a thing a source either does or does not do. The corpus is not like
# that: tests/stress_oracle.rs cannot run without it, while
# tests/buf_item_oracle.rs walks whatever images are there and names the
# corpus images among them. A grep sees the same string in both and
# would put the second in a tier `chore test` never runs, quietly
# dropping the log-item coverage it has without the corpus.
#
# tests/every_fixture_suite_is_run_gated.rs holds every name here to
# actually naming a corpus image, so the list cannot grow a suite that
# has nothing to do with it.
STRESS_SUITES="stress_oracle"

tier="${1:-}"
args=()
# The file as the classifier reads it: comment lines dropped, and
# double-quoted string literals emptied. A raw string (r#"..."#) is left
# alone, which is right — that is how the guest scripts are written, and
# the call around it is what is being read.
uncommented() {
    grep -vE '^[[:space:]]*//' "$1"
}

is_stress() {
    local suite
    for suite in $STRESS_SUITES; do [ "$suite" = "$1" ] && return 0; done
    return 1
}

for f in "$REPO"/tests/*.rs; do
    name="$(basename "$f" .rs)"
    text="$(uncommented "$f")"
    calls="$(printf '%s\n' "$text" | sed 's/"[^"]*"//g')"
    case "$tier" in
        unit)
            if ! is_stress "$name" &&
               ! printf '%s\n' "$text" | grep -qE "$FIXTURE" &&
               ! printf '%s\n' "$calls" | grep -qE "$TOOL|$KERNEL"; then
                args+=(--test "$name")
            fi
            ;;
        images)
            if printf '%s\n' "$text" | grep -qE "$FIXTURE" &&
               ! is_stress "$name" &&
               ! printf '%s\n' "$calls" | grep -qE "$TOOL|$KERNEL"; then
                args+=(--test "$name")
            fi
            ;;
        stress) is_stress "$name" && args+=(--test "$name") ;;
        # "EVERYTHING" IS NOT `cargo test` WITH NO ARGUMENTS, and that is
        # the whole of what this selection exists to say. A bare run also
        # selects tests/stress_oracle.rs, whose corpus `chore fixtures`
        # deliberately does not build — so the two runs that are meant to
        # be everything failed on three missing images instead:
        # `chore test:native`'s release pass, and the in-guest suite,
        # which is how a Mac reaches these tests at all.
        all) is_stress "$name" || args+=(--test "$name") ;;
        oracle)
            if printf '%s\n' "$calls" | grep -qE "$TOOL" &&
               ! printf '%s\n' "$calls" | grep -qE "$KERNEL"; then
                args+=(--test "$name")
            fi
            ;;
        kernel) printf '%s\n' "$calls" | grep -qE "$KERNEL" && args+=(--test "$name") ;;
        *) echo "usage: test-targets.sh unit|images|stress|oracle|kernel|all" >&2; exit 2 ;;
    esac
done
case "$tier" in
    unit|all) printf '%s\n' --lib --bins "${args[@]}" ;;
    *) printf '%s\n' "${args[@]}" ;;
esac
