#!/usr/bin/env bash
#
# vm-build-data-fixtures.sh — build POPULATED XFS filesystems in the
# oracle VM, together with a manifest of their contents generated by the
# Linux kernel itself.
#
# scripts/vm-build-fixtures.sh produces freshly-made filesystems, which
# have an empty short-form root directory and no file data at all. Those
# validate the superblock and AG headers and nothing else.
#
# These fixtures are mounted and written to, so they exercise the parts
# of the driver a user actually depends on: extent lists, multi-block
# files, sparse files, symlinks in both storage forms, and directories
# large enough to leave short form behind.
#
# The manifest beside each image is produced INSIDE Linux by the
# kernel's own XFS driver -- path, type, size and SHA-256 per entry.
# Nothing in this repository decides what the right answer is, which is
# the entire point: tests/endtoend_oracle.rs requires this driver to
# reproduce it byte for byte.
set -euo pipefail

REPO="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
"$REPO/scripts/vm.sh" up

# "<name>:<mkfs.xfs args>"
GEOMETRIES=(
    "default:"
    "1k:-b size=1024"
    "ftype:-m crc=1"
)

for geom in "${GEOMETRIES[@]}"; do
    name="${geom%%:*}"
    args="${geom#*:}"
    "$REPO/scripts/vm.sh" run "
        set -e
        cd /share
        img=xfsdata-$name.img
        rm -f \$img xfsdata-$name.manifest
        truncate -s 500M \$img
        if ! mkfs.xfs $args -f -q \$img >/dev/null 2>&1; then
            rm -f \$img
            echo 'SKIP  $name (mkfs.xfs rejected this geometry)'
            exit 0
        fi
        mnt=\$(mktemp -d)
        mount -o loop \$img \$mnt

        # A spread chosen to move the parts of the driver that a
        # single small file would leave untouched.
        echo 'hello world' > \$mnt/small.txt
        dd if=/dev/urandom of=\$mnt/medium.bin bs=4096 count=64 status=none
        dd if=/dev/urandom of=\$mnt/large.bin bs=1M count=8 status=none
        truncate -s 10M \$mnt/sparse.bin
        ln -s small.txt \$mnt/link-short
        ln -s \"\$(python3 -c 'print(\"d/\"*80+\"deep\")')\" \$mnt/link-long
        mkdir -p \$mnt/sub/nested
        echo nested > \$mnt/sub/nested/file.txt
        # 400 entries pushes this directory out of short form.
        mkdir \$mnt/manyfiles
        for i in \$(seq 1 400); do echo \$i > \$mnt/manyfiles/entry-\$i.txt; done
        # A file with more extents than fit in the inode, which is what
        # pushes its data fork from an inline list into a B+tree. Each
        # block is written with a hole in front of it so the extents
        # cannot be merged back into a shorter list.
        for i in \$(seq 0 199); do
            dd if=/dev/urandom of=\$mnt/fragmented.bin bs=4096 count=1 \
               seek=\$((i * 2)) conv=notrunc status=none
        done
        setfattr -n user.testattr -v testvalue \$mnt/small.txt 2>/dev/null || true
        sync
        umount \$mnt; rmdir \$mnt

        # Manifest, generated by the kernel driver on a read-only mount
        # so the image stays byte-identical to what was just written.
        mnt=\$(mktemp -d)
        mount -o ro,norecovery \$img \$mnt
        ( cd \$mnt
          find . -mindepth 1 | sort | while read -r p; do
            rel=\"\${p#.}\"
            if [ -L \"\$p\" ]; then
              printf '%s\\tlink\\t0\\t%s\\n' \"\$rel\" \"\$(readlink \"\$p\")\"
            elif [ -d \"\$p\" ]; then
              printf '%s\\tdir\\t0\\t-\\n' \"\$rel\"
            else
              printf '%s\\tfile\\t%s\\t%s\\n' \"\$rel\" \"\$(stat -c%s \"\$p\")\" \"\$(sha256sum \"\$p\" | cut -d' ' -f1)\"
            fi
          done
        ) > xfsdata-$name.manifest
        umount \$mnt; rmdir \$mnt

        # The root directory dump that tests/dir_oracle.rs compares
        # against, regenerated here so it can never describe an older
        # image than the one beside it. A stale dump is worse than a
        # missing one: it fails on a change that was intended, and passes
        # on one that was not.
        rootino=\$(xfs_db -r -c 'sb 0' -c 'print rootino' \$img 2>/dev/null | \
                  sed -n 's/^rootino = //p')
        {
            echo \"ROOTINO \$rootino\"
            xfs_db -r -c \"inode \$rootino\" -c print \$img 2>/dev/null
        } > xfsdata-$name.rootdump

        # Record which inodes ended up in B+tree format, straight from
        # the reference debugger. tests/endtoend_oracle.rs requires this
        # list to be non-empty: if a future mkfs or kernel keeps
        # fragmented.bin as an inline extent list, the fixture has
        # stopped exercising the bmbt walker and must say so rather than
        # passing quietly.
        : > xfsdata-$name.bmbt
        for f in fragmented.bin large.bin medium.bin; do
            ino=\$(xfs_db -r -c \"path /\$f\" -c \"print core.format\" \$img 2>/dev/null | \
                   sed -n 's/^core.format = //p')
            [ -n \"\$ino\" ] || continue
            printf '%s\\t%s\\n' \"/\$f\" \"\$ino\" >> xfsdata-$name.bmbt
        done

        echo \"BUILT $name (\$(wc -l < xfsdata-$name.manifest) entries, forks: \$(tr '\\n' ' ' < xfsdata-$name.bmbt))\"
    "
done

echo
echo "Now run: cargo test --test endtoend_oracle -- --nocapture"
